### ISSUE TITLE
EthList：众包维护的以太坊阅读清单

### ISSUE THREAD

**Issue by leviding** [xitu/blockchain-miner#1]
* 原文链接：[EthList: The Crowdsourced Ethereum Reading List](https://github.com/Scanate/EthList)
  * Markdown文件：[文件地址](https://github.com/xitu/blockchain-miner/blob/master/ethlist.md)
  * PR 地址：https://github.com/xitu/blockchain-miner/pull/4
  * **注意：本文是近期系列文章的目录，希望区块链行业的小伙伴认领本文，认真翻译，希望校对者也能提出更好的意见和建议。**
  ----
  * 翻译时间：4 天
  * 校对时间：2 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/blockchain-miner/wiki)

**Comment by StellaBauhinia** [comment]
翻译认领

**Comment by leviding** [comment]
@StellaBauhinia ok

**Comment by StellaBauhinia** [comment]
@leviding Hi有点问题
由于文章内容全都是链接，基本都粘在一起没有分隔，所以会自动聚集起来不利于校对。怎么整？
<img width="1143" alt="screen shot 2018-08-28 at 10 26 20 pm" src="https://user-images.githubusercontent.com/35908823/44729545-a83a8000-ab11-11e8-92f7-c607a9d6d4b3.png">

**Comment by leviding** [comment]
@StellaBauhinia 这样可以吧，差不多。用译文覆盖原文即可。
