### ISSUE TITLE
Your Official Guide to the Security Token Ecosystem

### ISSUE THREAD

**Issue by leviding** [xitu/blockchain-miner#11]
* 原文链接：[Your Official Guide to the Security Token Ecosystem](https://medium.com/@tatianakoffman/your-official-guide-to-the-security-token-ecosystem-61a805673db7)
  * Markdown文件：[文件地址](https://github.com/xitu/blockchain-miner/tree/master/article/0001/your-official-guide-to-the-security-token-ecosystem.md)
  * PR 地址：
  ----
  * 翻译时间：8 天
  * 校对时间：3 天
  * 翻译积分：9-11 分
  * 校对积分：3-6 分
  * [积分有什么用](https://github.com/xitu/blockchain-miner/wiki)

**Comment by leviding** [comment]
标题为：Security Token 生态 — 项目指南

**Comment by StellaBauhinia** [comment]
翻译认领

**Comment by leviding** [comment]
@StellaBauhinia 欢迎欢迎

**Comment by leviding** [comment]
@StellaBauhinia 这篇记得哈

**Comment by StellaBauhinia** [comment]
@leviding 好的。国庆前天天加班，这篇没排好时间，假期我弄一下。

**Comment by leviding** [comment]
@StellaBauhinia 记得这篇哈

**Comment by StellaBauhinia** [comment]
@leviding TAT抱歉这篇现在翻了一半，比我想象的难（为什么都是枯燥的项目3-5句话小简介……）

**Comment by leviding** [comment]
好的哈，按你的节奏来
