### ISSUE TITLE
ELI5：用简单的语言给小白解释什么是以太坊？

### ISSUE THREAD

**Issue by leviding** [xitu/blockchain-miner#3]
* 原文链接：[ELI5: What is Ethereum?](https://www.reddit.com/r/ethereum/comments/60hhjm/eli5_what_is_ethereum/)
  * Markdown文件：[文件地址](https://github.com/xitu/blockchain-miner/blob/master/article/0001/eli5-what-is-ethereum.md)
  * PR 地址：https://github.com/xitu/blockchain-miner/pull/6
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2.5-3.5 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/blockchain-miner/wiki)

**Comment by mingxing47** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@mingxing47 👌

**Comment by leviding** [comment]
@mingxing47 翻译的怎么样啦？

**Comment by mingxing47** [comment]
@leviding 今天提交pr

**Comment by leviding** [comment]
好的

**Comment by leviding** [comment]
@mingxing47 这篇翻译的怎么样了

**Comment by TrWestdoor** [comment]
@leviding 校对认领
