### ISSUE TITLE
什么是 Security Tokens（证券型代币）？

### ISSUE THREAD

**Issue by leviding** [xitu/blockchain-miner#7]
* 原文链接：[What are Security Tokens?](https://blockgeeks.com/guides/security-tokens/)
  * Markdown文件：[文件地址](https://github.com/xitu/blockchain-miner/blob/master/article/0001/security-tokens.md)
  * PR 地址：https://github.com/xitu/blockchain-miner/pull/18
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7-10 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/blockchain-miner/wiki)

**Comment by llp0574** [comment]
翻译认领

**Comment by leviding** [comment]
@llp0574 👌 好的，欢迎欢迎

**Comment by leviding** [comment]
好的哈，我就是提醒下，按你的时间来
