### ISSUE TITLE
2018 年 Security Token 发展现状及未来展望

### ISSUE THREAD

**Issue by leviding** [xitu/blockchain-miner#9]
* 原文链接：[Security Tokens in 2018: What Now, and What Next?](https://www.ccn.com/security-tokens-in-2018-what-now-and-what-next/)
  * Markdown文件：[文件地址](https://github.com/xitu/blockchain-miner/tree/master/article/0001/security-tokens-in-2018-what-now-and-what-next.md)
  * PR 地址：https://github.com/xitu/blockchain-miner/pull/17
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-2.5 分
  * [积分有什么用](https://github.com/xitu/blockchain-miner/wiki)

**Comment by StellaBauhinia** [comment]
翻译认领

**Comment by leviding** [comment]
@StellaBauhinia 欢迎欢迎
